# Generated by Django 3.2.9 on 2021-11-19 08:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('areas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deer',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='areas.district')),
            ],
        ),
        migrations.CreateModel(
            name='RideHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_start_at', models.DateTimeField()),
                ('use_end_at', models.DateTimeField()),
                ('use_end_lat', models.DecimalField(decimal_places=6, max_digits=10)),
                ('use_end_lng', models.DecimalField(decimal_places=6, max_digits=10)),
                ('use_deer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='deercorporation.deer')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
